### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by melodykramer**
Added public domain information to README.

### CODE REVIEW

**Comment by melodykramer** [comment]
Hey @jackiekazil - there is a LICENSE.md on this project. We're trying to standardize the READMEs themselves, so that people can see the licensing at a glance. I am happy to link to the LICENSE.md document within that - but am adding the Public Domain info to each README, so that our documentation is standard. [Example](https://github.com/18F/18f.gsa.gov#public-domain)

**Comment by jackiekazil** [comment]
@melodykramer so to clarify --- this is going to be added to EVERY README? along w/ the license in the repo? (If yes, then I will merge this to comply.)

**Comment by melodykramer** [comment]
Yup, I'm going in alphabetical order. (Good to audit, slow-going process.)

**Comment by jackiekazil** [comment]
Hahahaha ah.... got it..... it starts with numbers, but then it moves to 'a'. :-D

**Pull request merged**
